name: Build and release plugin
on:
  release:
    types: [published]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-swift:
    strategy:
      matrix:
        os: [self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Test Swift Package
        run: swift test
      - name: Build Swift Package
        run: swift build -c release
      - name: Archive Swift Package
        run: python3 package.py --folder=.build/release
      - name: Upload Swift Package
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: "*.zip"
  create-release:
    if: ${{ github.event.pusher.name != 'github action' }}
    runs-on: ubuntu-latest
    needs: build-swift
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.ref == 'refs/heads/main' }}
      - name: Create Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          branch: main
          dry_run: false
        if: ${{ github.ref == 'refs/heads/main' }}
